---
- name: Ensure firewalld is stopped and disabled
  ignore_errors: true
  become: true
  systemd:
    name: ufw
    state: stopped
    enabled: no

- name: Ensure firewalld is stopped and disabled
  ignore_errors: true
  become: true
  systemd:
    name: iptables
    state: stopped
    enabled: no

- name: Install basic utility packages using apt
  become: true
  apt:
    name:
      - net-tools
      - vim
      - nano
      - ssh
      - telnet
      - htop
      - curl
    state: present
    update_cache: yes

