--- 
### Zabbix UI
zabbix_groups:
  - "szcoders-corp"
  - "Windows Servers"
  - "Active Directory Hosts"

zabbix_templates:
  - "Windows by Zabbix agent"
  - "ICMP Ping"

# Zabbix UI Variables
host_ip: 10.0.0.2