--- 
#zabbix_url: "http://192.168.12.136/zabbix"
zabbix_url: "http://zabbix.ms.com/zabbix"
zabbix_user: "{{ zabbix_username }}"
zabbix_pass: "{{ zabbix_password }}"

# Host details
host_name: "{{ inventory_hostname }}"
visible_name: "{{ inventory_hostname }}"
host_ip: "{{ ansible_host }}"
group_name: "Linux servers"
template_name: "Kubernetes Kubelet by HTTP"

# Proxy details
proxy_name: "{{ inventory_hostname }}"
proxy_ip: "{{ ansible_host }}"
proxy_mode: 1          # 0 = active, 1 = passive
proxy_port: "10051"
proxy_group_name: "szcoders-dc"
proxy_hosts: []          # optional, list of host IDs to assign
proxy_id: 7
monitored_by: 0        # 0 = Zabbix Server, 1 = Zabbix Proxy
