--- 
#zabbix_url: "http://192.168.12.136/zabbix"
zabbix_url: "http://zabbix.ms.com/zabbix"
zabbix_user: "{{ zabbix_username }}"
zabbix_pass: "{{ zabbix_password }}"

# Host details
host_name: "{{ inventory_hostname }}"
visible_name: "{{ inventory_hostname }}"
host_ip: "{{ ansible_host }}"
group_name: "Linux servers"
template_name: "Kubernetes Kubelet by HTTP"

# Proxy details
proxy_name: "{{ inventory_hostname }}"
proxy_ip: "{{ ansible_host }}"
proxy_mode: 1
