---
- name: Deploy Zabbix Proxy 7.4
  hosts: zabbix-proxy
  become: true
  roles:
    - zabbix-proxy
  vars: 
    zabbix_server: "10.0.0.36"
    proxy_name: "szcoders-proxy"
    proxy_ip: "{{ ansible_host }}"
    proxy_mode: 1          # 0 = active, 1 = passive
    proxy_port: "10051"
    proxy_hosts: []          # optional, list of host IDs to assign


