---
# - name: Including task to add host to zabbix UI
#   include_tasks: add_host.yml

# - name: Including task to update macros to zabbix UI
#   include_tasks: update_macros.yml

- name: Including task to add host to zabbix UI
  include_tasks: add_host._by_proxy.yml